CREATE TABLE student(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	sex VARCHAR(10) NOT NULL,
	class INT NOT NULL,
	score INT NOT NULL,
	birthday INT NOT NULL
)
	
